// Control for M3: does a synthesized vertical touch scroll move the page (a) with no book mounted, (b) over the mounted book?
import { createServer } from 'vite';
import { chromium } from 'playwright-core';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const here = dirname(fileURLToPath(import.meta.url));
const server = await createServer({ configFile: join(here, 'vite.config.ts'), server: { port: 0, host: '127.0.0.1' } });
await server.listen();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
await page.goto(server.resolvedUrls.local[0]);
const cdp = await ctx.newCDPSession(page);
await page.evaluate(() => { document.documentElement.style.height = 'auto'; document.body.style.height = 'auto'; document.body.style.paddingBottom = '3000px'; });
const scroll = async () => { await page.evaluate(() => window.scrollTo(0, 0)); await cdp.send('Input.synthesizeScrollGesture', { x: 195, y: 400, yDistance: -400, gestureSourceType: 'touch', speed: 800 }); await page.waitForTimeout(500); return page.evaluate(() => window.scrollY); };
const out = {};
out.control_no_book_scrollY = await scroll();
await page.evaluate(() => window.__mount());
await page.waitForTimeout(300);
await page.evaluate(() => window.__events.splice(0));
const box = await page.locator('[data-phase]').boundingBox();
await page.evaluate(() => window.scrollTo(0, 0));
await cdp.send('Input.synthesizeScrollGesture', { x: box.x + box.width / 2, y: Math.min(box.y + box.height / 2, 800), yDistance: -400, gestureSourceType: 'touch', speed: 800 });
await page.waitForTimeout(500);
out.over_book_scrollY = await page.evaluate(() => window.scrollY);
out.over_book_events = await page.evaluate(() => window.__events.map((e) => e.name));
out.status = await page.getByTestId('status').textContent();
console.log(JSON.stringify(out));
await browser.close(); await server.close();
